baseURL = "http://neovatar.github.io/slides/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "reveal-hugo"
publishDir = "docs"
#relativeURLs = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "/reveal-hugo/themes/seligerit.css"
